version: "3.8"
services:
  contenedor-mysql: # Nombre de contenedor MYSQL
    container_name: contenedor-mysql
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: civilo_roller_db
    ports:
      - 33060:3306
  civilo_roller_app: 
    container_name: contenedor-civilo-roller-backend
    image: gerardoluceroc/imagen_civilo_roller_backend
    ports:
      - "8080:8080"
    environment:
    #Estas variables de entorno si bien estan escritas, aun no se ponen en el backend de spring boot
      - DB_URL=jdbc:mysql://contenedor-mysql:3306/civilo_roller_db
      - DB_USERNAME=root
      - DB_PASSWORD=admin
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - contenedor-mysql
